/*
 * Copyright © <2010>, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Eclipse Public License (EPL), version 1.0.  The full text of the EPL is at
 * http://www.opensource.org/licenses/eclipse-1.0.php.
 *
 */
// Modual name: ME_header.inc
//
// Global symbols define
//

/*
 * Constant
 */

define(`INTER_PART_MASK',               `0x7e000000')
define(`mpeg2_ref',		`r83')
define(`pic_ref',		`r82')
define(`INTRA16_DC_PRED',      `0xBB')
