/*
 * Copyright © <2010>, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Eclipse Public License (EPL), version 1.0.  The full text of the EPL is at
 * http://www.opensource.org/licenses/eclipse-1.0.php.
 *
 */
// Modual name: ME_header.inc
//
// Global symbols define
//

/*
 * Constant
 */

define(`INTER_PART_MASK',               `0x7e000000')
define(`mpeg2_ref',		`r83')
define(`pic_ref',		`r82')
define(`INTRA16_DC_PRED',      `0xBB')
/* Cost center ref */
define(`mv_cc_ref',		`r81')
define(`tmp_vme_wb0',              `r100')
define(`tmp_vme_wb1',              `r101')
define(`tmp_vme_wb2',              `r102')
define(`tmp_vme_wb3',              `r103')
define(`tmp_vme_wb4',              `r104')
define(`tmp_vme_wb5',              `r105')
define(`tmp_vme_wb6',              `r106')
define(`tmp_vme_wb7',              `r107')
define(`tmp_vme_wb8',              `r108')
define(`tmp_vme_wb9',              `r109')
